imports:
    - ../src/Manager/config/container.yml
    - ../../collection/config/package-container.yml
    - ../../route/config/package-container.yml
    - ../../form/config/package-container.yml
    - ../../bundle/config/package-container.yml
    - ../../db/config/package-container.yml
    - ../../pubsub/config/package-container.yml

services:
    slugify:
        class: Cocur\Slugify\Slugify