form:
    slug: manager-login
    storage:
        collection: login_attempts
        key: _id
    after: redirect
    redirect: /Manager
    fields:
        email:
            placeholder: Email
            display: fieldText@render
            required: true
        password:
            placeholder: Password
            display: fieldPassword@render
            required: true