imports:
    - ../../../../../uploadwrapper/config/containers/package-container.yml
    - helpers-container.yml

services:
    managerRoute:
        class:      Opine\Manager\Route
        arguments:  ['@route']
    managerController:
        class:      Opine\Manager\Controller
        arguments:  ['@managerModel', '@managerView', '@manager', '@form', '@search', '@uploadwrapper', '@slugify', '@route', '@redirect']
    managerApiController:
        class:      Opine\Manager\ApiController
        arguments:  ['@managerModel', '@form', '@search', '@uploadwrapper', '@slugify', '@route']
    managerModel:
        class:      Opine\Manager\Model
        arguments:  ['%root%', '@manager', '@db', '@bundleModel', '@collection', '@collectionModel', '@post', '@person']
    managerView:
        class:      Opine\Manager\View
        arguments:  ['@managerModel', '@layout']
